### ISSUE TITLE
Drupal_render has been removed

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mandrill#19]

**Comment by mshaver** [comment]
There appears to be only one place this is showing up still on the mandrill.admin.inc file. Looks like the new services class is "renderer"; 
https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21RendererInterface.php/function/RendererInterface%3A%3Arender/8

**Comment by jamidwyer** [comment]
This will be fixed by either https://github.com/thinkshout/mandrill/pull/48 or https://github.com/thinkshout/mandrill/pull/52. Both pull requests remove that file completely, as the admin form code is now in MandrillAdminSettingsForm.php. After removing, I've tested that Mandrill still sends emails.
