### ISSUE TITLE
Get MailChimp to show up in the list of modules that can use Mandrill to send mail

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mandrill#34]

**Comment by ruscoe** [comment]
Not sure if this refers to the Mail System module or to Mandrill. Maybe @unclegcb can clarify.

**Comment by Greg-Boggs** [comment]
This refers to the Mail System module, I believe.

**Comment by unclegcb** [comment]
right, but I suspect Mailchimp may need to have some code in place that registers it with the Mailsystem module.

**Comment by mortenson** [comment]
👋 Hi there - we're moving all existing Mandrill Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mandrill/issues/3031678
