### ISSUE TITLE
Make sure Mandrill Activity routing is correct

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mandrill#80]
Not always able to rely on entity type being the path here:

https://github.com/thinkshout/mandrill/blob/8.x-1.x/modules/mandrill_activity/src/Routing/MandrillActivityRoutes.php#L39

**Comment by mortenson** [comment]
👋 Hi there - we're moving all existing Mandrill Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mandrill/issues/3031676
