### ISSUE TITLE
Implement or remove mandrill_from()

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mandrill#81]
[mandrill_from()](https://github.com/thinkshout/mandrill/blob/8.x-1.x/mandrill.module#L249) isn't used anywhere in the D8 version of Mandrill.

The only place it would be needed is [here](https://github.com/thinkshout/mandrill/blob/8.x-1.x/src/Plugin/Mail/MandrillMail.php#L182).

Since it's only required in one place and there's already duplicate code, it might be worth just removing mandrill_from() entirely.

**Comment by mortenson** [comment]
👋 Hi there - we're moving all existing Mandrill Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mandrill/issues/3031675
